### PR TITLE
Add Chicory AOT mode to the benchmark

### PR DESCRIPTION
**Pull request by andreaTP**
Hi @shaunsmith :wave: and thanks a lot for starting this repository! :pray: 
Let me take the chance to open this for visibility over what is happening in Chicory those days.

Takeaways:

- the `interpreter` is a naive implementation, with almost zero optimizations done, the outcome is about as expected
- the `aot` should be pretty fast, the numbers are similar to `static-aot`
- the `static-aot` mode correctly runs and shows some good number on my noisy machine, it's built on top of [this PR](https://github.com/dylibso/chicory/pull/494) and you can reproduce building Chicory on [this bleeding edge branch](https://github.com/andreaTP/chicory/tree/build-benchmark)

Questions:

- do you have some specific machine where you are running the benchmark?
- if yes, I would love to, somehow, check the results, I'm happy to support this effort

### CODE REVIEW

**Comment by shaunsmith** [comment]
Hi @andreaTP, I set this up to educate myself and to create a framework for future comparisons so your addition of aot/static aot is welcome.  Is "aot" runtime Java bytecode generation and "static aot" build time generation?  Can you point me to some details?

I ran out of time getting the bleeding edge branch compiling.  Where wabt needs to be installed or configured wasn't clear.

I ran my simple benchmark on both an M1 Max MacBook and on an Oracle Cloud Infrastructure Linux VM.  Times differ but were proportionally consistent.  I tried to move the setup out of the test and perform sufficient warmup to test true peak.   Interestingly, Chicory ran almost 2x faster on the Graal JIT vs. C2.  But GraalWasm ran 51x faster with the Graal JIT thanks to Truffle compilation.  Obviously the benchmark is trivial so the results are inconclusive.  There's almost no WASM code run in this helloworld example.  But like I said, this is a start.  Here are the results I see on Linux (16 vCPU, 32GB) with GraalVM for JDK 21.0.4 (first with Graal JIT and then without--see run.sh).

```sh
Graal JIT (Truffle compilation)
Benchmark                    Mode  Cnt      Score      Error  Units
ChicoryTest.chicoryTest      avgt    3  47150.058 ± 8683.748  ns/op
GraalWasmTest.graalWasmTest  avgt    3    916.140 ±   12.778  ns/op

GraalWasm 47150/916 = ~51x faster


C2 (interpreter only)
Benchmark                    Mode  Cnt      Score      Error  Units
ChicoryTest.chicoryTest      avgt    3  75054.965 ± 4043.262  ns/op
GraalWasmTest.graalWasmTest  avgt    3  45362.124 ± 2246.936  ns/op
```
GraalWasm 75054/45362 = 1.65x

**Comment by andreaTP** [comment]
> I set this up to educate myself and to create a framework for future comparisons so your addition of aot/static aot is welcome.

That's amazing, thanks, I love to contribute to this effort!

> Is "aot" runtime Java bytecode generation and "static aot" build time generation?

That's correct, I don't have real docs about, as everything is still pretty experimental at this stage.
[This module](https://github.com/dylibso/chicory/tree/main/aot) is the "current" `aot` and it basically takes Wasm as input and directly emits bytecode.

> I ran out of time getting the bleeding edge branch compiling. Where wabt needs to be installed or configured wasn't clear.

That's sad to hear, my branch had a couple of minor issues, but it should compile out of the box on any machine.
I updated the branch and [checked in CI](https://github.com/andreaTP/chicory/actions/runs/10717693409).
If you face any issue building the Chicory project, :pray: please, [file an issue](https://github.com/dylibso/chicory/issues), and I'll follow up there.

Thanks for the details about how you run the benchmarks, I reverted the chicory version to the latest published `0.0.12`, removed the experimental bits, and only introduced the Aot mode so that we have a baseline to compare results.

It would be lovely if you can share the results, on the same(or comparable) HW, of this branch :slightly_smiling_face:

**Comment by shaunsmith** [comment]
Hi Andrea, I haven't had a chance to work this.  We can touch base on a call Alina is organizing.

**Comment by andreaTP** [comment]
Thanks for getting back, absolutely :+1:

**Comment by andreaTP** [comment]
Superseded by #2

**Pull request closed without merging**
