### PR TITLE
Update to Chicory 1.0.0-M2

### PR DESCRIPTION
**Pull request by andreaTP**
In this PR:

- I'm updating to Chicory `1.0.0-M2`
- removing the need for `wasi` in the Photon benchmark
- using a more recent version of TinyGo
- removing a couple of leftovers
- ~~increasing the iterations of both "Warmup" and "Measurament" to 10 trying to have more stable results~~

I believe those are improvements for the project setup and execution(independently from the WASM runtime used).
Happy to discuss any of those changes and revert when requested :slightly_smiling_face:

### CODE REVIEW

**Comment by shaunsmith** [comment]
@andreaTP  I see pretty stable numbers with 3 and 3.  Don't you?  I wonder if/why JMH doesn't support command line args to control warmup and test iterations?

**Comment by andreaTP** [comment]
I still see a lot of variation, but you are right it should be tunable on the command line.

I'll revert this change tomorrow :+1: does the rest of the changes look acceptable?

**Comment by shaunsmith** [comment]
Let me try out the changes.  I do think using Docker for the TinyGo build makes sense.  I'd rather require Docker than TinyGo be installed.  The same is true for the Photon Rust build. Locking down container image versions will make things more stable.  Of course that opens the door to testing with Docker/Podman/etc.

**Comment by andreaTP** [comment]
As agreed I reverted the iteration numbers.

> The same is true for the Photon Rust build

that's correct, I can follow up if you want to go full in :+1: .

> opens the door to testing with Docker/Podman/etc.

That's correct, but we are committing the results (at least for Go), I would say that, as long as it can run on GH Actions we are reasonably safe.

**Comment by shaunsmith** [comment]
I'll merge this and adjust docker run to support podman.  I'll follow that with an update to enable Graal JIT on OpenJDK distros.

**Comment by andreaTP** [comment]
> enable Graal JIT on OpenJDK distros.

Didn't know it's possible! Waiting for it!

**Pull request merged**
