### PR TITLE
Update Chicory and run in the 3 modes

### PR DESCRIPTION
**Pull request by andreaTP**
Chicory updated to the latest `1.0.0-M1` release.
I don't expect much variation in numbers across runtime/pre-compiled AOT as they are essentially different ways of "distributing" the same thing.

### CODE REVIEW

**Comment by shaunsmith** [comment]
@andreaTP I think you forgot to include "DemoMachineFactory".  It's referenced in ChicoryTest::doSetup.

**Comment by andreaTP** [comment]
@shaunsmith its generated in the `target/generated-sources` folder by the Maven plugin, are you having trouble compiling?

I'd recommend running a `mvn clean install` and syncing the Maven project in the IDE if that's out of date.

**Comment by shaunsmith** [comment]
Builds and runs in the terminal but VS Code is reporting an unresolved reference.  🤔

VS Code also has a warning for the pom.xml: "Plugin execution not covered by lifecycle configuration: com.dylibso.chicory:aot-maven-plugin-experimental:1.0.0-M1:wasm-aot-gen (execution: demo-plugin, phase: generate-sources)".  Not sure if it is relevant?

**Review by shaunsmith — APPROVED** [review]

**Comment by shaunsmith** [comment]
I've got another small benchmark I'll add and leverage your changes.

**Comment by andreaTP** [comment]
I think I know how to solve

 > VS Code is reporting an unresolved reference. 

I'll take a look also to:

> Plugin execution not covered by lifecycle configuration

Thanks for the report!

**Pull request merged**
